### ISSUE TITLE
Support for bundle packets

### ISSUE THREAD

**Issue by SkytAsul** [adepierre/SniffCraft#114]
For now, the content pane for the bundle packet shows an empty JSON object (`{}`). Is it possible to show the content of those packets?

**Comment by adepierre** [comment]
Not sure what you'd like to see as this packet as no content so there is nothing to display. Also note that this packet is a purely protocol one made to ensure the client process a group of packets in the same tick and it's in no way related to the in-game bundles that can store items.

**Comment by SkytAsul** [comment]
That's precisely what I want to see: the packets _inside_ the bundle packet. Or is it already the case?

**Comment by adepierre** [comment]
There is no other packet inside. It's just used as a delimiter so you need to look at the packets that came before/after.

**Comment by SkytAsul** [comment]
Oooh okay sorry about that! I based myself on the Java server implementation of it, which is a record class containing other packets.
Thanks for the answers!
