### ISSUE TITLE
[Version request]

### ISSUE THREAD

**Issue by 0x0x0xzzzzz** [adepierre/SniffCraft#136]
### Minecraft version

1.7.10

**Comment by adepierre** [comment]
1.7.10 is not a supported version as the protocol is not implemented.

**Comment by 0x0x0xzzzzz** [comment]
please implement it

**Comment by adepierre** [comment]
Not planned

**Comment by 0x0x0xzzzzz** [comment]
then plane it please

**Comment by 0x0x0xzzzzz** [comment]
Can you list me some starting point for me to dev it ?

**Comment by adepierre** [comment]
Check the implementation for the other versions [here](https://github.com/adepierre/Botcraft/tree/master/protocolCraft/include/protocolCraft), find the differences between the first supported version (1.12.2) and 1.12.1 then 1.12 then all 1.11 versions etc... down to 1.7.10 and implement them one by one incrementally for each packet.
