### ISSUE TITLE
Can we sniff for old minecraft pe version run on android

### ISSUE THREAD

**Issue by craftstudiogames** [adepierre/SniffCraft#3]
Hi @adepierre 
Could you please support sniffcraft to capture data in old minecraft pe version like 0.13, 0.14 ?
Thank you so much!

**Comment by adepierre** [comment]
You could adapt sniffcraft for this usecase but you would need an implementation of the protocol of this specific version.

I am not aware of such an implementation and I don't have time (or interest) to do it myself. But if you want to make a PR I could review it to include it nicely into sniffcraft.
