### ISSUE TITLE
Failed to build with game version 1.16.5

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/SniffCraft#4]
Packets
```
ServerboundClientIntentionPacket
ClientboundGameProfilePacket
ClientboundLoginCompressionPacket
ClientboundHelloPacket
```
are not present in ProtocolCraft for version 1.16.5.
On commit `b38b519` everything works fine

**Comment by adepierre** [comment]
These packets definitely exist in ProtocolCraft (see for example [ClientboundHelloPacket](https://github.com/adepierre/Botcraft/blob/master/protocolCraft/include/protocolCraft/Messages/Login/Clientbound/ClientboundHelloPacket.hpp)).

Did you use a clean clone or an existing one? If this is an older one, you might want to update the botcraft submodule to the latest commit.

**Comment by maxsupermanhd** [comment]
I updated submodule and repo, they are in sync, this was existing clone.

**Comment by adepierre** [comment]
Does it work now or is the issue still here?
