### ISSUE TITLE
Replay mod support

### ISSUE THREAD

**Issue by uis246** [adepierre/SniffCraft#5]
Maybe useless for package ispection software, but in some cases it useful. For example if you have bot and want to see actions of other players or something like this.

Implementation example:
https://github.com/uis246/AltCraft-tools/blob/master/TransperentProxy/replaymod.c
(Yep. Another proxy)
It works with crushedpixels' replaymod.
Replay contains only clientbound packets, so no client representation without injection move packets to replay.

https://github.com/ReplayMod/ReplayMod/blob/57c7362e3417ec563235a3e41a300e4a2ab9a709/src/main/java/com/replaymod/recording/handler/RecordingEventHandler.java

**Comment by adepierre** [comment]
I'm affraid I'm not familiar with replay mods and things like that. Could you elaborate?

Is that what you're calling a replay mod just a way to resend the packets in the same order they arrive at the right time? So basically it's just saving the packets and their timestamps in a binary file and reading this file and sending back the packets on demand?

**Comment by uis246** [comment]
> Is that what you're calling a replay mod just a way to resend the packets in the same order they arrive at the right time? So basically it's just saving the packets and their timestamps in a binary file and reading this file and sending back the packets on demand?

Kind of. Record packets with timestamp and length in big endian uint32_t, save metadata(name, version and UUIDs of players) in json and compress to single zip. Now replay mod can read it and render world.

**Comment by adepierre** [comment]
Ok thanks, it should be possible to implement that. Is there any official/formal documentation/description of this format somewhere?

**Comment by uis246** [comment]
AFAIK there are partial description from dev on repmod forum.
Format of recording.tmcpr
{big endian 32 bit timestamp(defference between current time and first packet), big endian 32 bit packet size(Wanna a 4GB packet? :)), data[size](decrypted and decompressed, packetid and later)}
Later recording.tmcpr and metaData.json compressed to zip archive and extension changed to .mcpr.
Move to .minecraft/replay_recordings or .minecraft/replay download. Ready to replay(with same version of course).

You can also ask dev at discord server: https://discord.gg/SwEeC7ye

**Comment by adepierre** [comment]
Yes I ended up asking on the discord server. I'm currently working on it. In fact I have a version that could work, but it makes me find small erros in protocolCraft that I have to fix at the same time 😁

**Comment by adepierre** [comment]
Sessions can now be exported to a replay mod file, with the exception of the current player that can't be displayed. See [readme](https://github.com/adepierre/SniffCraft/blob/master/README.md#replay-mod) for more information.
