### ISSUE TITLE
Add encryption by having the sniffer join as client

### ISSUE THREAD

**Issue by Youded-byte** [adepierre/SniffCraft#6]
Let me explain; BotCraft is capable of joining a server using encryption, and is capable of decrypting all packets as well.  What stops us from when the player connects to our proxy server ( in offline mode ), to encrypt and forward all packets to the server we are connecting to. All packets we receive could be decrypted and forwarded to the client. 

Pakkit ( https://github.com/Heath123/pakkit ) is a nodejs program that relies on node-minecraft-protocol ( https://github.com/PrismarineJS/node-minecraft-protocol ) and is capable of doing this, and manipulating packets as well.

The same method used by pakkit should be possible using the excellent ProtocolCraft as well.

**Comment by adepierre** [comment]
Done with 3ce1f1f
