### ISSUE TITLE
Legacy console edition support

### ISSUE THREAD

**Issue by ListLostLisp** [adepierre/SniffCraft#60]
It would be really nice to make sense of the packets for the legacy console editions like the psvita and the xbox360. It is possible to capture this using two ps3 emulators using rpcn. They use udp p2p. From what I have read it is almost a direct port of the java version.

There is a re project that could be helpful though it is far from done.
 https://github.com/GRAnimated/MinecraftLCE

**Comment by adepierre** [comment]
Hello, this is outside of the scope of this project. Sniffcraft only works with Java Edition, and not with any of the other versions (Bedrock, Pocket, Console or whatever). As I do not use these versions I won't work on them and as such they'll probably never be supported.

**Comment by adepierre** [comment]
Closing as answered
