### ISSUE TITLE
error when starting?

### ISSUE THREAD

**Issue by cupiditys** [adepierre/SniffCraft#8]
builds fine but when i try to start it says "The code execution cannot proceed because zlib.dll was not found."

**Comment by adepierre** [comment]
It means that you already have zlib installed on your system, so cmake finds it and use it. However, the zlib version you have is a dynamically built one, so you need to either copy zlib.dll next to sniffcraft exe, or add the location of the zlib.dll file to your system path.

If you want sniffcraft to build a static version locally for you, you can also comment [this line](https://github.com/adepierre/SniffCraft/blob/master/cmake/zlib.cmake#L4) and start a fresh build. It should solve your issue.

**Comment by cupiditys** [comment]
commenting that line didnt work but just adding zlib.dll did, thanks
