### ISSUE TITLE
stuck on authentication completed

### ISSUE THREAD

**Issue by cupiditys** [adepierre/SniffCraft#9]
probably just doing something wrong but when i launch it outputs this and then stops
```
Loading updated conf file
Missing or malformed cached credentials for Mojang account with login <email>, sending credentials to get a new one...
Sending credentials to Mojang authentication server...
Authentication completed!
```

**Comment by adepierre** [comment]
Unfortunately, I can't reproduce the error on my side everything works as intended.

Could you share more information on what exactly you did and try to do?

On my side this is the path I used trying to reproduce your issue:

- start a local vanilla 1.18.1 server with online-mode set to true
- fresh build of sniffcraft
- conf file with Online set to true, MojangLogin set with my email address and MojangPassword set with my minecraft password
- starting sniffcraft
- here I get the same output you put in your message, with ``Authentication completed!`` on the last line. The program is now waiting for a connection
- I connect with the official vanilla client to 127.0.0.1:<sniffcraft port>

And at this point the connection is opened and everything works as expected.

**Comment by cupiditys** [comment]
ah i didnt see i had to connect to 127.0.0.1, makes sense thanks

log to console works now, but trying to use log to replay (usually) immediately kicks me; server console says either `"Internal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: inflate data is bad"` or `Internal Exception: io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit`. if it doesnt immediately kick then it will after like 20 seconds saying `Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 72 is below server threshold of 256` and give me this error 
![image](https://user-images.githubusercontent.com/66990287/147834417-8f825e63-a80e-4e38-ae49-1ca7a330a514.png)

**Comment by adepierre** [comment]
I've just pushed a little fix, I'm not sure this is the root cause of your issue, but if you can still try it out with the latest commit to be sure.

Also, if it doesn't send any packet it might be a firewall issue? Make sure you don't have sniffcraft blocked for out packets in you firewall configuration.

**Comment by cupiditys** [comment]
still seems to have same issue, completely turned off firewall

**Comment by adepierre** [comment]
I'm afraid I'm out of idea on this one. And without a way to reproduce the issue on my side, there is not much more I can do to help unfortunately.

**Comment by cupiditys** [comment]
yea weird since it does initially load chunks/items when i join but nothing after

**Comment by adepierre** [comment]
Did you have a chance to get more data on this issue? I've tried again to reproduce it but it works fine on both my computer and VMs I tried on.

**Comment by cupiditys** [comment]
nope i have no idea but i was using fabric (no mods) if that changes anything

**Comment by adepierre** [comment]
Just tested again with latest 1.18.1 fabric server, still working on my side. This is weird.

**Comment by adepierre** [comment]
Closing it for inactivity. Feel free to post more information if you have some.
